---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.maestro.rbac.serviceAccountName }}
{{- if .Values.maestro.rbac.createServiceAccountTokenSecret }}
secrets:
  - name: {{ .Release.Name }}-maestro-k8s-secret
{{ end }}
{{- if .Values.maestro.rbac.createServiceAccountTokenSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-maestro-k8s-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.maestro.rbac.serviceAccountName }}
type: kubernetes.io/service-account-token
{{ end }}
{{- if .Values.maestro.rbac.ClusterRoleBindingCreate }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maestro-cluster-role
  # "namespace" omitted since ClusterRoles are not namespaced
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.maestro.rbac.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.maestro.rbac.serviceAccountName }}
  namespace: {{ .Values.maestro.rbac.serviceAccountNamespace }}
roleRef:
  kind: ClusterRole
  name: maestro-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{ else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: maestro-role
    namespace: {{ .Values.maestro.rbac.serviceAccountNamespace }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.maestro.rbac.serviceAccountName }}
  namespace: {{ .Values.maestro.rbac.serviceAccountNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.maestro.rbac.serviceAccountName }}
  namespace: {{ .Values.maestro.rbac.serviceAccountNamespace }}
roleRef:
  kind: Role
  name: maestro-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
