# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sinker
spec:
  selector:
    app: {{ .Release.Name }}
    component: sinker
  ports:
    - protocol: TCP
      port: {{ .Values.sinker.httpPort }}
      name: {{ .Release.Name }}-sinker-http
